const examples = [
  {
    'subject': 'Er',
    'verb': 'würde',
    'es-das': 'das',
    'nicht-2': 'nicht',
    'last': 'vergessen',
    'source': 'https://forum.duolingo.com/comment/4052671/Er-w%C3%BCrde-das-nicht-vergessen',
  }, {
    'subject': 'Ich',
    'verb': 'bin',
    'nicht-1': 'nicht',
    'todo': 'die Professorin',
    'source': 'https://forum.duolingo.com/comment/572120/Ich-bin-nicht-die-Professorin',
  }, {
    'subject': 'Ich',
    'verb': 'hätte',
    'manner': 'gern',
    'direct': 'ein Pils und eine Brezel',
    'source': 'https://forum.duolingo.com/comment/11192261/Ich-h%C3%A4tte-gern-ein-Pils-und-eine-Brezel',
  }, {
    'subject': 'Ich',
    'verb': 'stimme',
    'personal': 'dir',
    'time': 'in diesem Punkt',
    'nicht-1': 'nicht',
    'last': 'zu',
    'source': 'https://forum.duolingo.com/comment/3318671/Ich-stimme-dir-in-diesem-Punkt-nicht-zu',
  }, {
    'subject': 'Ich',
    'verb': 'werde',
    'personal': 'dich',
    'time': 'nie',
    'last': 'vergessen',
    'source': 'https://forum.duolingo.com/comment/2732200/I-will-never-forget-you',
  }, {
    'subject': 'Ich',
    'verb': 'werde',
    'direct': 'euch',
    'last': 'bitten',
    'zu-verb': 'zu gehen',
    'source': 'https://forum.duolingo.com/comment/1532320/Ich-werde-euch-bitten-zu-gehen',
  }, {
    'subject': 'Ich',
    'verb': 'würde',
    'es-das': 'es',
    'personal': 'mir',
    'nicht-1': 'nicht',
    'last': 'wünschen',
    'source': 'https://forum.duolingo.com/comment/5450596/Ich-w%C3%BCrde-es-mir-nicht-w%C3%BCnschen',
  }, {
    'subject': 'Sie',
    'verb': 'stellt',
    'personal': 'mich',
    'indirect': 'ihrem Bruder',
    'nicht-2': 'nicht',
    'last': 'vor',
    'source': 'https://forum.duolingo.com/comment/1454811/Sie-stellt-mich-ihrem-Bruder-nicht-vor',
  }, {
    'subject': 'Wir',
    'verb': 'werden',
    'es-das': 'es',
    'time': 'niemals',
    'last': 'erfahren',
    'source': 'https://forum.duolingo.com/comment/2650378/Wir-werden-es-niemals-erfahren',
  }, {
    'subject': 'Er',
    'verb': 'wird',
    'es-das': 'es',
    'personal': 'uns',
    'time': 'bis heute Abend',
    'last': 'gesagt haben',
    'source': 'https://forum.duolingo.com/comment/13558555/Er-wird-es-uns-bis-heute-Abend-gesagt-haben',
  }, {
    'subject': 'Ihr',
    'verb': 'werdet',
    'time': 'im Dezember',
    'direct': 'das Produkt',
    'last': 'gekauft haben',
    'source': 'https://forum.duolingo.com/comment/11847640/You-will-have-bought-the-product-in-December',
  }, {
    'subject': 'Ich selbst',
    'verb': 'würde',
    'sich': 'mich',
    'es-das': 'das',
    'time': 'niemals',
    'last': 'trauen',
    'source': 'https://www.bayerische-staatszeitung.de/staatszeitung/leben-in-bayern/detailansicht-leben-in-bayern/artikel/ich-selbst-wuerde-mich-das-niemals-trauen.html#topPosition',
  }
];
