var adjectives = {
  abwechslungsreich: null,
  aktuell: null,
  amüsant: null,
  authentisch: null,
  bilderreich: null,
  ereignisreich: null,
  gefühlvoll: null,
  grausam: null,
  gruselig: null,
  handlungsarm: null,
  humorvoll: null,
  informativ: null,
  interessant: null,
  langweilig: null,
  lehrreich: null,
  lustig: null,
  reißerisch: null,
  romantisch: null,
  sachlich: null,
  temporeich: null,
  traurig: null,
  turbulent: null,
  uninteressant: null,
  unsachlich: null,
  unterhaltsam: null,
  witzig: null,
};
