var verbs = {
  "abbauen": ["Aufgebautes unter Erhaltung des Materials zwecks Wiederverwendung in seine Einzelteile zerlegen; herabsetzen, senken"],
  "abbekommen": ["sein Teil von etwas bekommen; der Einwirkung von etwas (Positivem) unterliegen"],
  "abreißen": ["durch [ruckhaftes] Reißen [von jemandem, sich oder etwas] lösen, abtrennen; [bei jemandem, sich oder etwas] hastig, mit einem Ruck entfernen"],
  "abschaffen": ["aufheben (3a), außer Kraft setzen, beseitigen, was bisher bestand, üblich war; aus der Welt schaffen"],
  "abschieben": ["von seinem Platz, seiner Stelle schiebend entfernen; gerichtlich des Landes verweisen"],
  "abschreiben": ["(von etwas, was schriftlich oder gedruckt vorliegt) eine Abschrift machen; etwas [was im Konzept vorliegt] ins Reine schreiben; noch einmal schreiben"],
  "abstimmen": ["durch Abgabe der Stimmen eine Entscheidung über etwas herbeiführen; [etwas] in Einklang mit etwas bringen"],
  "abtrocken": ["(mit einem Handtuch o. Ä.) trocken reiben; (Nasses, Feuchtes) wegwischen"],
  "abwaschen": ["mithilfe von Wasser [und Seife] beseitigen; mithilfe von Wasser säubern"],
  "andenken": ["gedanklich gegen etwas angehen; beginnen über etwas nachzudenken, sich über etwas Gedanken zu machen"],
  "anfassen": ["mit der Hand berühren, ergreifen, mit den Fingern befühlen; bei der Hand nehmen"],
  "ankommen": ["einen Ort erreichen, an einem Ort eintreffen"],
  "ankündigen": ["das Kommen, Stattfinden, Erscheinen o. Ä. (von etwas) im Voraus mitteilen; (als Sache) durch bestimmte Anzeichen das Herannahen erkennen lassen"],
  "anlocken": ["(aufgrund seiner reizvollen Beschaffenheit) an einen bestimmten Ort locken, ziehen, anziehende Wirkung auf jemanden ausüben"],
  "anmeckern": ["grundlos, in kleinlicher Weise kritisieren, [dauernd] der Kritik unterwerfen"],
  "anpassen": ["jemandem, einer Sache anmessen; für jemanden, etwas passend machen; etwas einer Sache angleichen; etwas auf etwas abstimmen"],
  "anschalten": ["durch Betätigen eines Schalters o. Ä. in Betrieb setzen; durch eine automatische Schaltung in Betrieb gesetzt werden"],
  "ansehen": ["den Blick auf jemanden, etwas richten; ins Gesicht blicken, betrachten; etwas [aufmerksam, prüfend] betrachten (um es kennenzulernen)"],
  "ansehen": ["den Blick auf jemanden, etwas richten; ins Gesicht blicken, betrachten; etwas [aufmerksam, prüfend] betrachten (um es kennenzulernen)"],
  "anspringen": ["sich mit einem Sprung auf jemanden oder ein Tier stürzen; anfallen; an jemandem hochspringen"],
  "anstellen": ["an etwas stellen; sich einer wartenden Reihe von Personen anschließen"],
  "aufbrauchen": ["völlig, bis auf den letzten Rest verbrauchen"],
  "aufessen": ["essen, ohne etwas übrig zu lassen; alles, was vorhanden oder auf dem Teller ist, essen"],
  "aufgeben": ["zur Weiterleitung, Beförderung, Bearbeitung übergeben; als Schularbeit auftragen"],
  "aufkommen": ["[unvermutet] entstehen; entstehende Kosten übernehmen"],
  "aufladen": ["(Ladegut) auf ein Transportmittel laden"],
  "auflösen": ["(in einer Flüssigkeit) zerfallen, zergehen lassen; sich zerteilen"],
  "aufnehmen": ["vom Boden zu sich heraufnehmen; "],
  "aufpassen": ["aufmerksam sein, achtgeben; beaufsichtigend auf jemanden, etwas achthaben, um einen Schaden o. Ä. zu verhüten"],
  "aufschlagen": ["im Fall hart auftreffen, aufprallen; durch Aufschlagen (1) verletzen"],
  "aufschreiben": ["schriftlich festhalten; niederschreiben; notieren"],
  "aufstellen": ["in einer bestimmten Ordnung o. Ä., an einen vorgesehenen Platz stellen, hinstellen; Aufstellung nehmen [lassen]; postieren"],
  "auspressen": ["durch Pressen herausholen, herausfließen lassen; aus etwas durch Pressen die darin enthaltene Flüssigkeit austreten lassen, herausholen"],
  "ausrutschen": ["auf einer glatten Fläche aus dem Gleichgewicht kommen, keinen Halt finden (und hinfallen); etwas nicht richtig festhalten können, und deshalb damit die gewünschte Tätigkeit nicht mehr durchführen können."],
  "aussetzen": ["an einen Ort bringen [und dort sich selbst überlassen]; "],
  "befreien": ["durch Überwinden von Widerständen [gewaltsam] aus Gefangenschaft, einer unangenehmen, schlimmen Lage o. Ä. herausholen, jemandem Freiheit verschaffen; einen erfolgreichen Freiheitskampf führen und dadurch von etwas frei machen"],
  "begleiten": ["mit jemandem, etwas zur Gesellschaft, zum Schutz mitgehen, mitfahren; an einen bestimmten Ort bringen, führen; gleichzeitig, eng verbunden mit etwas vorhanden sein, auftreten; mit etwas einhergehen"],
  "belästigen": ["stören, jemandem zur Last fallen; unbequem, lästig werden; bedrängen; jemandem gegenüber zudringlich werden"],
  "belegen": ["etwas (mit etwas) bedecken, (mit einem Belag) versehen; beschießen"],
  "beleidigen": ["(durch eine Äußerung, Handlung) in seiner Ehre angreifen, verletzen"],
  "beschießen": ['[längere Zeit hindurch] auf jemanden, etwas schießen; Elementarteilchen auf etwas auftreffen lassen'],
  "bestäuben": ["mit etwas Pulvrigem, Staubartigem bestreuen, überziehen; durch Übertragung von Blütenstaub befruchten"],
  "besteuern": ["mit Steuern belegen"],
  "betreffen": ["für jemanden, etwas gelten, von Bedeutung sein, sich auf jemanden beziehen; angehen; treffen; widerfahren; zustoßen"],
  "durchwachsen": ["aus mageren und fetten Schichten bestehend; "],
  "einführen": ["vorsichtig, sachgerecht in eine Öffnung, durch eine Öffnung in etwas schieben; (Waren) aus dem Ausland beziehen, kaufen; importieren"],
  "einräumen": ["[in einer bestimmten Anordnung] hineinstellen oder -legen; mit Gegenständen, die (in einen Schrank, Raum usw.) hineingehören, versehen, ausstatten"],
  "einstürzen": ["in sich zusammenfallen, so dass die Einzelteile direkt übereinander und unten am Boden liegen; eine Person befallen, ohne dass diese genügend Zeit hat, den Vorgang kontrollieren zu können"],
  "entgegenwirken": ["sein Wirken, seine Wirkung gegen etwas einsetzen"],
  "entmündigen": ["(jemandem) das Recht entziehen, bestimmte juristische Handlungen auszuführen"],
  "erfahren": ["durch eigenes Erleben kennen lernen"],
  "erfüllen": ["[sich ausbreitend einen Raum allmählich] ganz und gar [aus]füllen; mit etwas ausfüllen"],
  "erheben": ["in die Höhe heben; emporstrecken; erbauen"],
  "ermitteln": ["durch [geschicktes] Nachforschen herausfinden, feststellen; errechnen, feststellen"],
  "ermutigen": ["(jemandem zu etwas Bestimmtem) Mut machen, ihn in seinem Vorhaben bestärken"],
  "erschweren": ["(durch Widerstand, Hindernisse o. Ä.) schwierig, mühevoll machen; Schwierigkeiten bei etwas bereiten"],
  "kennzeichnen": ["mit einem Kennzeichen (2a) versehen; jemanden, etwas durch Aufzeigen seiner Kennzeichen (1) in seiner Eigenart beschreiben, darstellen; charakterisieren"],
  "mitmachen": ["bei etwas (mit) dabei sein; an etwas [aktiv] teilnehmen; sich einer Unternehmung anschließen, sich an etwas beteiligen"],
  "teilnehmen": ["bei etwas (einer Handlung, einem Ablauf, einem Geschehen) dabei sein; beiwohnen; aktiver Teilnehmer an einer bestimmten Unternehmung, Veranstaltung sein"],
  "überkleben": ["etwas auf etwas kleben und es dadurch verdecken"],
  "überlegen": ["mit einem bestimmten Ziel nachdenken, in Gedanken versinken, etwas überdenken"],
  "überprüfen": ["nochmals prüfen, ob etwas in Ordnung ist, seine Richtigkeit hat, funktioniert; nochmals überdenken, durchdenken"],
  "überschmieren": ["etwas über eine Fläche zu schmieren, häufig im Sinne von etwas ungleichmäßig oder unsauber zu bedecken"],
  "überzeugen": ["jemandem durch Argumente Gewissheit über etwas verschaffen; jemanden durch Argumente dahin bringen, dass er etwas für wahr oder notwendig hält; in seiner Leistung den Erwartungen voll entsprechen"],
  "umsetzen": ["an eine andere Stelle, auf einen anderen Platz setzen"],
  "verabreden": ["eine bestimmte Abmachung mit jemandem treffen, einen bestimmten Plan, eine bestimmte Vorgehensweise festlegen; eine Zusammenkunft mit jemandem verabreden"],
  "verbringen": ["sich (für eine bestimmte Zeitdauer an einem Ort o. Ä.) aufhalten, verweilen; eine bestimmte Zeit (auf bestimmte Weise) zubringen, hinbringen; eine bestimmte Zeit auf etwas verwenden"],
  "verdienen": ["als Entschädigung für geleistete Arbeit in Form von Lohn, Gehalt, Honorar o. Ä. erwerben; einen bestimmten Verdienst haben"],
  "vereinbaren": ["abmachen (2), verabreden (1), in einem gemeinsamen Beschluss festlegen; in Übereinstimmung, in Einklang bringen (meist verneint)"],
  "verfolgen": ["durch Hinterhergehen, -eilen zu erreichen [und einzufangen] suchen; jemandem zur Last fallen; jemanden bedrängen"],
  "verhaften": ["(aufgrund eines Haftbefehls) festnehmen"],
  "verheiraten": ["eine Ehe eingehen, die Ehe mit jemandem schließen; (jemandem) zur Ehe geben"],
  "verklagen": ["gegen jemanden vor Gericht klagen, einen Rechtsanspruch geltend machen; sich über jemanden bei jemandem beschweren"],
  "vermehren": ["an Menge, Anzahl o. Ä. größer machen; an Menge, Anzahl o. Ä. größer werden"],
  "vermissen": ["sich mit Bedauern bewusst sein, dass jemand, etwas nicht mehr in der Nähe ist, nicht mehr zur Verfügung steht, und dies als persönlichen Mangel empfinden; das Fehlen von etwas bemerken"],
  "verpacken": ["zum Transport (in etwas) packen, (in etwas) unterbringen"],
  "verpassen": ["nicht rechtzeitig da sein, kommen und deshalb nicht erreichen, nicht antreffen; ungenutzt vorübergehen lassen, sich entgehen lassen"],
  "verschießen": ["als Munition, Geschoss beim Schießen verwenden; "],
  "verschließen": ["mit einem Schloss o. Ä. zumachen, schließen, sichern; durch Zuschließen unzugänglich machen; mithilfe eines Gegenstandes, einer Vorrichtung o. Ä. bewirken, dass etwas nach außen hin fest zu ist"],
  "versehen": ["dafür sorgen, dass jemand etwas bekommt, hat; versorgen; "],
  "versöhnen": ["mit jemandem nach einem Streit wieder Frieden schließen, sich vertragen; (zwei miteinander im Streit liegende Personen, Parteien) veranlassen, sich zu vertragen, Frieden zu schließen"],
  "verstecken": ["(jemanden, etwas) heimlich an einem unbekannten Ort unterbringen, sodass die Person oder Sache nicht gesehen wird"],
  "verteilen": ["[aufteilen und in einzelnen Anteilen, Portionen o. Ä.] an mehrere Personen vergeben, austeilen"],
  "verzerren": ["in entstellender Weise verziehen (1a); bewirken, dass sich jemandes Gesicht o. Ä.verzerrt (1a)"],
  "vorkommen": ["[überraschend] geschehen, sich ereignen, passieren; jemandem [als etwas Neues] begegnen, von jemandem erfahren werden"],
  "vornehmen": ["nach vorn nehmen, bewegen"],
  "vorschreiben": ["als Muster, Vorlage niederschreiben; als Vorlage für eine spätere Reinschrift schreiben"],
  "wegwerfen": ["etwas auf den Boden fallen und liegen lassen; etwas, was man nicht mehr braucht, in den Müll werfen"],
  "zureden": ["(jemanden) durch Worte veranlassen wollen, etwas Bestimmtes zu tun; (jemanden) durch Reden beeinflussen"],
  "zwangseinweisen": ["als Zwangseinweisung bezeichnet man in Deutschland eine Einweisung in ein Krankenhaus, eine Psychiatrie oder in ein Pflegeheim, die ohne Zustimmung des Patienten erfolgt (durch Zwang)"],
};
