var verbs = {
  "abbauen": ["Aufgebautes unter Erhaltung des Materials zwecks Wiederverwendung in seine Einzelteile zerlegen; herabsetzen, senken"],
  "abbekommen": ["sein Teil von etwas bekommen; der Einwirkung von etwas (Positivem) unterliegen"],
  "abschreiben": ["(von etwas, was schriftlich oder gedruckt vorliegt) eine Abschrift machen; etwas [was im Konzept vorliegt] ins Reine schreiben; noch einmal schreiben"],
  "abtrocken": ["(mit einem Handtuch o. Ä.) trocken reiben; (Nasses, Feuchtes) wegwischen"],
  "abwaschen": ["mithilfe von Wasser [und Seife] beseitigen; mithilfe von Wasser säubern"],
  "andenken": ["gedanklich gegen etwas angehen; beginnen über etwas nachzudenken, sich über etwas Gedanken zu machen"],
  "anfassen": ["mit der Hand berühren, ergreifen, mit den Fingern befühlen; bei der Hand nehmen"],
  "ankommen": ["einen Ort erreichen, an einem Ort eintreffen"],
  "ankündigen": ["das Kommen, Stattfinden, Erscheinen o. Ä. (von etwas) im Voraus mitteilen; (als Sache) durch bestimmte Anzeichen das Herannahen erkennen lassen"],
  "anlocken": ["(aufgrund seiner reizvollen Beschaffenheit) an einen bestimmten Ort locken, ziehen, anziehende Wirkung auf jemanden ausüben"],
  "anmeckern": ["grundlos, in kleinlicher Weise kritisieren, [dauernd] der Kritik unterwerfen"],
  "ansehen": ["den Blick auf jemanden, etwas richten; ins Gesicht blicken, betrachten; etwas [aufmerksam, prüfend] betrachten (um es kennenzulernen)"],
  "ansehen": ["den Blick auf jemanden, etwas richten; ins Gesicht blicken, betrachten; etwas [aufmerksam, prüfend] betrachten (um es kennenzulernen)"],
  "anstellen": ["an etwas stellen; sich einer wartenden Reihe von Personen anschließen"],
  "aufessen": ["essen, ohne etwas übrig zu lassen; alles, was vorhanden oder auf dem Teller ist, essen"],
  "aufladen": ["(Ladegut) auf ein Transportmittel laden"],
  "aufschlagen": ["im Fall hart auftreffen, aufprallen; durch Aufschlagen (1) verletzen"],
  "aufschreiben": ["schriftlich festhalten; niederschreiben; notieren"],
  "auspressen": ["durch Pressen herausholen, herausfließen lassen; aus etwas durch Pressen die darin enthaltene Flüssigkeit austreten lassen, herausholen"],
  "erfahren": ["durch eigenes Erleben kennen lernen"],
  "verbringen": ["sich (für eine bestimmte Zeitdauer an einem Ort o. Ä.) aufhalten, verweilen; eine bestimmte Zeit (auf bestimmte Weise) zubringen, hinbringen; eine bestimmte Zeit auf etwas verwenden"],
  "verdienen": ["als Entschädigung für geleistete Arbeit in Form von Lohn, Gehalt, Honorar o. Ä. erwerben; einen bestimmten Verdienst haben"],
  "verfolgen": ["durch Hinterhergehen, -eilen zu erreichen [und einzufangen] suchen; jemandem zur Last fallen; jemanden bedrängen"],
  "verheiraten": ["eine Ehe eingehen, die Ehe mit jemandem schließen; (jemandem) zur Ehe geben"],
  "vermissen": ["sich mit Bedauern bewusst sein, dass jemand, etwas nicht mehr in der Nähe ist, nicht mehr zur Verfügung steht, und dies als persönlichen Mangel empfinden; das Fehlen von etwas bemerken"],
  "verpacken": ["zum Transport (in etwas) packen, (in etwas) unterbringen"],
  "verpassen": ["nicht rechtzeitig da sein, kommen und deshalb nicht erreichen, nicht antreffen; ungenutzt vorübergehen lassen, sich entgehen lassen"],
  "verschlossen": ["[durch Ver- oder Zuschließen] unzugänglich gemacht; sehr zurückhaltend, in sich gekehrt; wortkarg"],
  "verstecken": ["(jemanden, etwas) heimlich an einem unbekannten Ort unterbringen, sodass die Person oder Sache nicht gesehen wird"],
  "verteilen": ["[aufteilen und in einzelnen Anteilen, Portionen o. Ä.] an mehrere Personen vergeben, austeilen; aufteilen und in gleicher Menge oder Anzahl an verschiedene Stellen bringen, legen, stellen usw., irgendwo unterbringen"],
  "wegwerfen": ["etwas auf den Boden fallen und liegen lassen; etwas, was man nicht mehr braucht, in den Müll werfen"],
};
